# Generated by Django 3.2.4 on 2021-06-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20210630_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='changed',
            field=models.DateTimeField(auto_now=True, verbose_name='Changed'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
    ]
