# Generated by Django 3.2.4 on 2021-07-01 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20210701_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_attempts_to_solve',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Attempts To Solve'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_of_points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Number of Points'),
        ),
    ]
