# Generated by Django 3.2.4 on 2021-07-03 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=255, null=True, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_attempts_to_solve',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Attempts To Solve'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=2048, verbose_name='Question'),
        ),
    ]
