# Generated by Django 3.2.4 on 2021-07-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['created'], 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
    ]
