version: "3.6"

services:
  math-tutor-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_USER: ${PG_DATABASE_USER}
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}
    volumes:
      - math-tutor-postgres:/var/lib/postgresql/data

volumes:
  math-tutor-postgres: